version: '3.0'
services:
  tb-gateway:
    restart: always
    build: .
    # Ports (Required for REST connector)
    ports:
      - "1883:1883"
    volumes:
      - ~/.tb-gateway/config:/thingsboard_gateway/config
      - ~/.tb-gateway/logs:/thingsboard_gateway/logs
