thingsboard:
  host: <put host>
  port: 8081
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: false
    statsSendPeriodInSeconds: 3600
    configuration: statistics/statistics_linux.json
  deviceFiltering:
    enable: false
    filterFile: list.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 200
  minPackSizeToSend: 500
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
    inactivityTimeoutSeconds: 120
    inactivityCheckPeriodSeconds: 10
  security:
    accessToken: <put access token>
  qos: 1
  connection:
    keepAlive: 120
    minReconnectDelay: 10
    timeout: 120
redis:
  host: <put host>
  port: 6379
  password: <put password>
