mqtt:
  thingsboard:
    host: <put host>
    port: 8081
    accessToken: <put access token>
    qos: 1
    connection:
      keepAlive: 120
      minReconnectDelay: 10
      timeout: 120
  mosquitto:
    host: <put host>
    port: 1883
    connection:
      keepAlive: 120
      minReconnectDelay: 10
      timeout: 120

redis:
  host: <put host>
  port: 6379
  password: <put password>

aiServer:
  host: <put host>
  accessToken: <put access token>
  uploadPeriodSec: 60

heartRate:
  calculator:
    jobsPerProcess: 10
