thingsboard:
  host: <host>
  port: 8081
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: false
  deviceFiltering:
    enable: false
    filterFile: list.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 200
  minPackSizeToSend: 500
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
  security:
    accessToken: <access token>
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
grpc:
  enabled: false
  serverPort: 9595
  keepaliveTimeMs: 10000
  keepaliveTimeoutMs: 5000
  keepalivePermitWithoutCalls: true
  maxPingsWithoutData: 0
  minTimeBetweenPingsMs: 10000
  minPingIntervalWithoutDataMs: 5000
connectors:
  - name: Mosquitto Broker
    type: mqtt
    configuration: mqtt.json
