thingsboard:
  host: a3480422f7d584c65aaf2b9fa258fead-500139692.ap-northeast-2.elb.amazonaws.com
  port: 8081
  remoteShell: false
  remoteConfiguration: false
  statistics:
    enable: false
  deviceFiltering:
    enable: false
    filterFile: list.json
  maxPayloadSizeBytes: 1024
  minPackSendDelayMS: 200
  minPackSizeToSend: 500
  checkConnectorsConfigurationInSeconds: 60
  handleDeviceRenaming: true
  checkingDeviceActivity:
    checkDeviceInactivity: false
  security:
    accessToken: m8tBNRYCf8vMKLzlKtfd
  qos: 1
storage:
  type: memory
  read_records_count: 100
  max_records_count: 100000
connectors:
  - name: Mosquitto Broker
    type: mqtt
    configuration: mqtt.json
